// UI
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SELECT_SIDEBAR_ITEM = 'SELECT_SIDEBAR_ITEM'

// STATUS
export const GET_STATUS = 'GET_STATUS'
export const GET_STATUS_RESPONSE = 'GET_STATUS_RESPONSE'

// AUTH
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL'

// Trade
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT'
export const GET_HISTORY = 'GET_HISTORY'
export const GET_HISTORY_RESPONSE = 'GET_HISTORY_RESPONSE'
export const GET_WATCHLIST = 'GET_WATCHLIST'
export const GET_WATCHLIST_RESPONSE = 'GET_WATCHLIST_RESPONSE'