// UI
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SELECT_SIDEBAR_ITEM = "SELECT_SIDEBAR_ITEM";

// AUTH
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";
